### ISSUE TITLE
Spec: Make a title bar API

### ISSUE THREAD

**Issue by Lamparter** [IviriusCommunity/Rebound#23]
### 📄 Description

> For title bar API:
> - add comments
> - add `IsInRect(x, y, width, height)` bool
> - remove unnecessary code
> - write docs on the website

### ⚡ API Changes

_Coming soon!_

### 👥 Usage scenarios

_Coming soon!_

### 🔙 Backward Compatibility

_Not rated to affect backwards compatibility_

### 🤔 Difficulty

Medium

**Comment by IviriusMain** [comment]
This API will make it easier to integrate custom caption buttons in Rebound apps and there will also be docs on how to use this in other projects.

**Comment by IviriusMain** [comment]
The API itself is finished, only the docs are left.

**Comment by Lamparter** [comment]
We need to establish better docs.

**Comment by Lamparter** [comment]
```cs
// TODO: Create docs for titlebar API
```
