### ISSUE TITLE
Bug: Shortcuts disappear

### ISSUE THREAD

**Issue by Lamparter** [IviriusCommunity/Rebound#24]
### 🪟 What OS build is this issue present?

Windows 11

### 🔢 What version are you on?

`v0.0.3` (latest)

### 📄 Description

> For shortcuts despawning:
> - not sure what happens here, they randomly disappear on (un)installation

### 🤔 Expected behavior

_Shortcuts should not despawn_

### ⚒️ Did you find any workaround?

_Not yet_

**Comment by IviriusMain** [comment]
Fixed
