### ISSUE TITLE
Feature: Change title bar in TPM Configuration

### ISSUE THREAD

**Issue by Lamparter** [IviriusCommunity/Rebound#25]
### 📄 Description

> For TPM title bar:
> - see #23

**Comment by IviriusMain** [comment]
This will be worked on after https://github.com/IviriusCommunity/Rebound/issues/23 is finished.

**Comment by Lamparter** [comment]
@IviriusMain?

**Comment by IviriusMain** [comment]
Yes I'm working on it

**Comment by IviriusMain** [comment]
Done
