### ISSUE TITLE
Spec: Add PCR values to TPM Configuration

### ISSUE THREAD

**Issue by Lamparter** [IviriusCommunity/Rebound#28]
### 📄 Description

_Coming soon!_

### ⚡ API Changes

_Coming soon!_

### 👥 Usage scenarios

_Coming soon!_

### 🔙 Backward Compatibility

_Coming soon!_

### 🤔 Difficulty

Medium

**Comment by jarno9981** [comment]
Hi

**Comment by jarno9981** [comment]
Api i being rewriten will release tonight

**Comment by jarno9981** [comment]
bug is fixed with latest api changes pcr now shows value 
[TpmManagerFinal.zip](https://github.com/user-attachments/files/17332755/TpmManagerFinal.zip)
use the tpmmanager.cs in rebound tpm

**Comment by jarno9981** [comment]
![Image](https://github.com/user-attachments/assets/f0ad190e-6318-4cf7-b478-7ce6ac20c73f)
🥳
