### ISSUE TITLE
Spec: Add features to Appearance and Personalization section in Control Panel

### ISSUE THREAD

**Issue by Lamparter** [IviriusCommunity/Rebound#30]
### 📄 Description

> FOR APPEARANCE AND PERSONALIZATION:
> - help wanted
> - a lot of stuff to do

Couldn't be bothered to use British spelling in title since _some_ people are against it... American Imperialism smh

### ⚡ API Changes

_Coming soon!_

### 👥 Usage scenarios

_Coming soon!_

### 🔙 Backward Compatibility

_Not rated to affect backwards compatibility_

### 🤔 Difficulty

High

**Comment by IviriusMain** [comment]
This is technically ready for release
