### ISSUE TITLE
Feature: Remove `ps1` file creation from Defrag

### ISSUE THREAD

**Issue by Lamparter** [IviriusCommunity/Rebound#32]
### 📄 Description

_Coming soon!_

### 🗃️ Alternative solutions

_Coming soon!_

### ⚡ API Changes

_Coming soon!_

### 👥 Intended Use-Case

_Coming soon!_

### ✅ Tasks

_Coming soon!_

### 📸 Assets

_Coming soon!_

**Comment by IviriusMain** [comment]
Done!
