### ISSUE TITLE
Bug: Not all licence holders are displayed in `Rebound.About`

### ISSUE THREAD

**Issue by Lamparter** [IviriusCommunity/Rebound#39]
### 🪟 What OS build is this issue present?

Microsoft®️ Windows®️ Version 23H2 (OS Build 22631.4249)
©️ Microsoft Corporation. All rights reserved.

The Windows 11 Pro operating system and its user interface are protected by trademark and other pending or existing intellectual property rights in the United States and other countries/regions.

This product is licensed under the [Microsoft Software License Terms](https://support.microsoft.com/en-us/windows/microsoft-software-license-terms-e26eedad-97a2-5250-2670-aad156b654bd) to: 

`[redacted]`

### 🔢 What version are you on?

[`4577ab0`](https://github.com/IviriusCommunity/Rebound/commit/4577ab0b11f58c3a0e6b2d1297e58433a318bb1d)

### 📄 Description

Rebound About "Rebound Winver" does not display all of the licence-holders who own a Microsoft Windows Software License on the computer, and only displays the first one.

### 🪜 Steps To Reproduce

1. Own a computer with more than one licence holder
2. Open Rebound Winver
3. See the error
4. _(optionally)_ Open `winver.exe` to view the system default "About Windows" dialog and compare

### 🤔 Expected behavior

All licence-holders should be displayed in Rebound About

### Affected platforms

🪟 Windows

### ⚒️ Did you find any workaround?

No. The correct licence holders are not printed into the clipboard when that button is pressed either.

### 📸 Assets

![image](https://github.com/user-attachments/assets/60a2f5b8-66e2-4603-92e4-3ab8611a8c9d)

As you can see, `winver` displays both my email (redacted) and `Scan Computers` (sometimes displays as `CN=Scan Computers, O=Scan Computers International Limited, C=UK`), however Rebound About only displays my email and not `Scan Computers`, my computer's manufacturer.

**Comment by Lamparter** [comment]
This is an easy fix, all that needs to be done is to include the `org` registry ID as well as the `user` one.

**Comment by IviriusMain** [comment]
Added, will close this issue now.
