### ISSUE TITLE
Clicking the "up" button when the Rebound 11 control panel is on its home page opens the file explorer

### ISSUE THREAD

**Issue by willyblah** [IviriusCommunity/Rebound#4]
https://github.com/user-attachments/assets/b08e31c1-97a1-4f8e-8a9d-eb3387e797f1

Here is a video of the issue

**Comment by IviriusMain** [comment]
This is normal behavior. Clicking the up button is meant to navigate to the root directory, and since there's none, it will navigate to the default first page of file explorer. The same thing also happens in the legacy Control Panel.
