### ISSUE TITLE
Rebound 11 doesn't build on release

### ISSUE THREAD

**Issue by Lamparter** [IviriusCommunity/Rebound#55]
I thought this was a problem with the CI, but this is actually a problem with the build configuration. Rebound doesn't build when set to release mode (only 7/9, rather than on Debug the full 9/9)

```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(5034,5): error MSB3030: Could not copy the file "C:\Users\runneradmin\.nuget\packages\microsoft.web.webview2\1.0.2646-prerelease\build\..\\runtimes\win-anycpu\native_uap\Microsoft.Web.WebView2.Core.dll" because it was not found. [D:\a\Rebound\Rebound\Rebound\Rebound.csproj]
```

_Originally posted by @Lamparter in https://github.com/IviriusCommunity/Rebound/discussions/22#discussioncomment-10858161_

**Comment by Lamparter** [comment]
@IviriusMain can you reproduce this by setting your build configuration to `x64|Release` and selecting all projects in Solution Explorer and hitting `Rebuild`?

**Comment by Lamparter** [comment]
I can't replicate how Visual Studio is able to build it - commands like `dotnet build -c Debug` and `msbuild /p:Configuration=Debug /r` don't work at all...

**Comment by IviriusMain** [comment]
😭
