### ISSUE TITLE
Seemingly uncritical error during installation

### ISSUE THREAD

**Issue by grandeljay** [IviriusCommunity/Rebound#60]
### 🪟 What OS build is this issue present?

AtlasOS v.0.3.2 (based on Windows 11 Pro v10.0.22631 Build 22631)

### 🔢 What version are you on?

Rebound 11 v0.0.3. ALPHA

### 📄 Description

I downloaded the installer from GitHub and ran the Rebound 11 Installation, hitting the "Install" button. The following message appeared:
![image](https://github.com/user-attachments/assets/362aacbd-437e-4a58-b42b-20acb6653324)

### 🪜 Steps To Reproduce

Assuming you have the same desktop environment as mentioned above:
1. Download ReboundHubInstaller.exe from the latest GitHub releases
2. Run the installer
3. Navigate to Rebound 11
4. Click Install

### 🤔 Expected behavior

I expected the installation to run without any error.

### Affected platforms

🪟 Windows

### ⚒️ Did you find any workaround?

Yes, everything seems to work as it should. I still need to restart my PC but will report if there are more issues. This issue is merely an FYI, feel free to close if it has little or no value.

### 📸 Assets

![image](https://github.com/user-attachments/assets/362aacbd-437e-4a58-b42b-20acb6653324)

**Comment by Lamparter** [comment]
I'm going to imagine this is a problem with atlasOS and not Rebound, but I'll leave the issue open if you have anything else to report 🙂

**Comment by IviriusMain** [comment]
This error might be related to P/Invoke

**Comment by grandeljay** [comment]
I found a way to reproduce the error message on my system:
1. Open Rebound Control Panel
2. Click on the "System & Security" tab on the left
3. Hit the navigate up button at the top 
![image](https://github.com/user-attachments/assets/41e9b35d-ba28-4f34-9196-7afd551dc8cb)

**Comment by IviriusMain** [comment]
This might be a memory allocation error, @Lamparter do you think this is related to AtlasOS?

**Comment by Lamparter** [comment]
Almost certainly is, though there could be one more thing: @grandeljay have you/or AtlasOS modified the File Explorer behaviour/replaced it with an alternative?

**Comment by grandeljay** [comment]
By now I also have [Files](https://files.community/) installed but the error first appeared before I had it installed

**Comment by Lamparter** [comment]
I'm assuming this is an error with AtlasOS, @grandeljay if you have any more information feel free to share.
